# Generated by Django 3.0.8 on 2020-08-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_1', '0003_patient_pgender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='psymptom',
            new_name='psymptom1',
        ),
        migrations.AddField(
            model_name='patient',
            name='psymptom2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='psymptom3',
            field=models.TextField(null=True),
        ),
    ]
