# Generated by Django 3.0.8 on 2020-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_1', '0002_auto_20200824_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pgender',
            field=models.CharField(default='男', max_length=5),
        ),
    ]
